# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0003_create_custom_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anno',
            name='anno_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='anno',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
