# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anno',
            fields=[
                ('anno_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(default='catch_v0.1', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(max_length=128)),
                ('creator_name', models.CharField(max_length=128)),
                ('anno_text', models.TextField(null=True)),
                ('anno_format', models.CharField(default='text/html', max_length=128)),
                ('anno_deleted', models.BooleanField(default=False)),
                ('anno_permissions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('platform_target_id', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=128)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('anno_reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anno.Anno')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('context_id', models.CharField(max_length=128)),
                ('collection_id', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_source', models.CharField(max_length=256, null=True)),
                ('target_format', models.CharField(max_length=128)),
                ('target_media', models.CharField(max_length=128)),
                ('target_selector', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('target_scope', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('anno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anno.Anno')),
            ],
        ),
        migrations.AddField(
            model_name='anno',
            name='anno_tags',
            field=models.ManyToManyField(to='anno.Tag'),
        ),
        migrations.AddField(
            model_name='anno',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anno.Platform'),
        ),
    ]
