# Generated by Django 2.2 on 2019-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0005_auto_20171019_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anno',
            name='schema_version',
            field=models.CharField(default='1.2.0', max_length=128),
        ),
    ]
