# Generated by Django 2.2.4 on 2020-05-30 19:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0006_auto_20190701_1508'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='anno',
            name='anno_raw_gin',
        ),
        migrations.AddIndex(
            model_name='anno',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=False, fields=['raw'], name='anno_raw_gin'),
        ),
    ]
