# Generated by Django 2.2.4 on 2020-05-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0007_auto_20200530_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='anno',
            name='collection_id',
            field=models.CharField(default='default', max_length=1024),
        ),
        migrations.AddField(
            model_name='anno',
            name='context_id',
            field=models.CharField(default='default', max_length=1024),
        ),
        migrations.AddField(
            model_name='anno',
            name='platform_name',
            field=models.CharField(default='default', max_length=128),
        ),
        migrations.AddField(
            model_name='anno',
            name='target_source_id',
            field=models.CharField(default='default', max_length=2048),
        ),
    ]
