# Generated by Django 2.2.4 on 2020-05-31 00:48

from django.db import migrations


def extract_platform_fields(apps, schema_editor):
    AnnoModel = apps.get_model('anno', 'Anno')
    for row in AnnoModel.objects.all():
        catcha = row.raw
        row.platform_name = catcha['platform']['platform_name']
        row.context_id = catcha['platform']['context_id']
        row.collection_id = catcha['platform']['collection_id']
        row.target_source_id = catcha['platform']['target_source_id']
        row.save(update_fields=[
            'platform_name', 'context_id', 'collection_id', 'target_source_id'])

class Migration(migrations.Migration):
    dependencies = [
        ('anno', '0008_add_platform_fields'),
    ]

    operations = [
        migrations.RunPython(
            extract_platform_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

