# Generated by Django 2.2.4 on 2020-05-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0009_populate_platform_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anno',
            name='collection_id',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='anno',
            name='context_id',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='anno',
            name='platform_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='anno',
            name='target_source_id',
            field=models.CharField(max_length=2048),
        ),
    ]
