# Generated by Django 2.2.4 on 2020-06-01 18:46

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anno', '0011_auto_20200601_1422'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='anno',
            name='anno_raw_gin',
        ),
        migrations.AddIndex(
            model_name='anno',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=True, fields=['raw'], name='anno_raw_gin'),
        ),
    ]
