# Generated by Django 4.2.10 on 2024-02-22 23:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("consumer", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="CatchpyProfile",
        ),
    ]
